htmlsitemap and seocore added with coding standard
dssjignesh/m2-html-sitemap pull request #1
Opened 2024-08-14 10:44 UTC by priyankavasoya

@harishmk1805 
please check

2024-08-14 11:24 UTC, harishmk1805 requested changes
please check phtml file proper

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Helper/Data.php
> +            $categoryDisable = $this->scopeConfig->getValue('dss_htmlsitemap/category/id_category', $this->scopeStore);
if used multiple times use as variable

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Helper/Data.php
> +        $enableCategory = $this->scopeConfig->isSetFlag('dss_htmlsitemap/category/enable_category', $this->scopeStore);
if used multiple times use as variable

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Helper/Data.php
> +        $enableProduct = $this->scopeConfig->isSetFlag('dss_htmlsitemap/product/enable_product', $this->scopeStore);
if used multiple times use as variable

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Model/Config/Source/Order.php
> +
remove space

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Observer/AfterCategorySave.php
> +
remove unused space

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/Setup/Patch/Data/SitemapProduct.php
> +                'source' => \Dss\HtmlSiteMap\Model\Config\Product\ExcludeHtmlSiteMap::class,
use Dss\HtmlSiteMap\Model\Config\Product\ExcludeHtmlSiteMap;

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/etc/acl.xml
> +<!-- /**
????

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/etc/adminhtml/system.xml
> + *
remove commet from xml

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/layout/sitemap_product_list.xml
> +    <update handle="sitemap_index_index" />
why used update?

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/additional_list.phtml
> +if ($additionUrlCount != null): ?>
please formate phtml use <?php if(): ?>

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/additional_list.phtml
> +                if ($openNewTab == 1) {
formate phtml

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/custom.phtml
> +            <?= /* @noEscape */  $escaper->escapeHtml($titleSiteMap); ?>
why used /* @noEscape */ ??

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/custom_top.phtml
> +            <?= /* @noEscape */  $escaper->escapeHtml($titleSiteMap); ?>
why used /* @noEscape */

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/product_list.phtml
> +    <h2 class="dss_h2"><?= /* @noEscape */ $titleProduct; ?></h2>
remove /* @noEscape */

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/store_list.phtml
> +if ($enableStoreView): ?>
formate phtml as per coding standards

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/store_list.phtml
> +        <?php
<?php endforeach; ?>
    </div>
    <?php endif; ?>

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/SeoCore/Block/Validate.php
> +        protected Context $context,
remove protected it's required?

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/SeoCore/Helper/Data.php
> +    public function getStoreManager(): \Magento\Store\Model\StoreManagerInterface
use Magento\Store\Model\StoreManagerInterface;

2024-08-14 11:24 UTC, harishmk1805 commented on app/code/Dss/SeoCore/etc/adminhtml/system.xml
> +            <label><![CDATA[Dss Commerce SEO]]></label>
remove

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Block/CategoryCollection.php
> +    public function getCmsPages(): \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
Done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Block/ItemsCollection.php
> +    public function getHelper(): \Dss\HtmlSiteMap\Helper\Data
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Block/ItemsCollection.php
> +        $this->scopeConfig = $context->getScopeConfig();
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Block/ProductCollection.php
> +
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Controller/Index/Index.php
> +        protected Context $context,
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Helper/Data.php
> +            $categoryDisable = $this->scopeConfig->getValue('dss_htmlsitemap/category/id_category', $this->scopeStore);
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Helper/Data.php
> +        $enableProduct = $this->scopeConfig->isSetFlag('dss_htmlsitemap/product/enable_product', $this->scopeStore);
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Model/Config/Source/Order.php
> +
done

2024-08-20 07:06 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Observer/AfterCategorySave.php
> +
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/Setup/Patch/Data/SitemapProduct.php
> +                'source' => \Dss\HtmlSiteMap\Model\Config\Product\ExcludeHtmlSiteMap::class,
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/etc/acl.xml
> +<!-- /**
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/etc/adminhtml/system.xml
> + *
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/layout/sitemap_product_list.xml
> +    <update handle="sitemap_index_index" />
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/additional_list.phtml
> +if ($additionUrlCount != null): ?>
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/additional_list.phtml
> +                if ($openNewTab == 1) {
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/custom.phtml
> +            <?= /* @noEscape */  $escaper->escapeHtml($titleSiteMap); ?>
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/custom_top.phtml
> +            <?= /* @noEscape */  $escaper->escapeHtml($titleSiteMap); ?>
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/product_list.phtml
> +    <h2 class="dss_h2"><?= /* @noEscape */ $titleProduct; ?></h2>
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/SeoCore/etc/adminhtml/system.xml
> +            <label><![CDATA[Dss Commerce SEO]]></label>
done

2024-08-20 07:07 UTC, priyankavasoya commented on app/code/Dss/SeoCore/Helper/Data.php
> +    public function getStoreManager(): \Magento\Store\Model\StoreManagerInterface
done

2024-08-20 07:08 UTC, priyankavasoya commented on app/code/Dss/SeoCore/Block/Validate.php
> +        protected Context $context,
done

2024-08-20 07:08 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/store_list.phtml
> +        <?php
done

2024-08-20 07:08 UTC, priyankavasoya commented on app/code/Dss/HtmlSiteMap/view/frontend/templates/store_list.phtml
> +if ($enableStoreView): ?>
done

2024-08-21 04:18 UTC, harishmk1805 approved these changes

2024-08-21 04:18 UTC, merged